name: Build for windows

on:
  - push
  - pull_request

jobs:
  build_wheels:
    name: Build wheel on Windows ${{ matrix.config.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - name: MSVC x64
            vs-arch: amd64
            py-architecture: x64

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Install Python 3.10
        with:
          python-version: "3.10"
          architecture: ${{ matrix.config.py-architecture }} 

      - uses: actions/setup-python@v4
        name: Install Python 3.9
        with:
          python-version: "3.9"
          architecture: ${{ matrix.config.py-architecture }}

      - uses: actions/setup-python@v4
        name: Install Python 3.8
        with:
          python-version: "3.8"
          architecture: ${{ matrix.config.py-architecture }}

      - uses: actions/setup-python@v4
        name: Install Python 3.7
        with:
          python-version: "3.7"
          architecture: ${{ matrix.config.py-architecture }}

      - uses: actions/setup-python@v4
        name: Install Python 3.6
        with:
          python-version: "3.6"
          architecture: ${{ matrix.config.py-architecture }}

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.3

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Test for Python 3.10
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.vs-arch }}
          tox -e py310

      - name: Test for Python 3.9
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.vs-arch }}
          tox -e py39

      - name: Test for Python 3.8
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.vs-arch }}
          tox -e py38

      - name: Test for Python 3.7
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.vs-arch }}
          tox -e py37

      - name: Test for Python 3.6
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -no_logo -arch=${{ matrix.config.vs-arch }}
          tox -e py36

      - name: Build wheel
        if: contains(github.ref, 'tags/')
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v1
        if: contains(github.ref, 'tags/')
        with:
          name: wheels
          path: ./wheelhouse
